module.exports = {
  admin_books: require('./admin/books'),
  admin_parts: require('./admin/parts'),
  admin_questions: require('./admin/questions'),
  admin_users: require('./admin/users'),
  alerts: require('./alerts'),
  books: require('./books'),
  customToasts: require('./customToasts'),
  keeps: require('./keeps'),
  likes: require('./likes'),
  main: require('./main'),
  notifications: require('./notifications'),
  parts: require('./parts'),
  questions: require('./questions'),
  signIn: require('./signIn'),
  toasts: require('./toasts'),
  users: require('./users'),
};
